---
title: "Model selection"
author: ""
format:
  beamer:
    engine: tectonic
    colortheme: beaver
    incremental: false
    aspectratio: 169
---

## Data

```{r load data}
library(mgcv)
library(terra)

# Load occurrence data
d <- read.csv("../data/occurrences.csv") 

# Load climate data
ff <- paste0(
  "../data/",
  paste0("wc2.1_10m_bio_", c(1, 4, 12, 15), ".tif")
)
r <- ff |> rast() |> crop(ext(-13, 33, 33, 62))
```

## First model

```{r full-enm}
enm1 <- gam(
  occ ~ s(wc2.1_10m_bio_1, k = 5) +
    s(wc2.1_10m_bio_4, k = 5) + 
    s(wc2.1_10m_bio_12, k = 20) +
    s(wc2.1_10m_bio_15, k = 5),
  data = d,
  family = "binomial"
)
```

## Build all possible ENMs

```{r dredge}
vars <- names(r)
n <- sum(sapply(2:4, \(m) dim(combn(vars, m))[2]))
enm <- as.list(rep(NA, n))
for (m in 2:4) {
  combs <- combn(vars, m)
  cat(sprintf("\t%d variables\t%d combinations\n", m, dim(combs)[2]))
  for (i in seq_len(dim(combs)[2])) {
    form <- paste0("s(", combs[, i], ", k = 5)")
    form <- paste(form, collapse = " + ")
    form <- as.formula(paste0("occ ~ ", form))
    enm[[min(which(is.na(enm)))]] <- gam(form, data = d, family = "binomial")
  }
}
```

## Model selection
```{r selection}
aic <- data.frame(
  formula = sapply(enm, \(x) as.character(x$formula)[3]),
  AIC = sapply(enm, \(x) AIC(x))
)
aic$DeltaAIC <- aic$AIC - min(aic$AIC)
head(aic[order(aic$AIC), c("AIC", "DeltaAIC")], n = 3)
aic$formula[which.min(aic$AIC)]
```
